Traceback (most recent call last):
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def plot_binary_images(image: np.ndarray, thresholds: list):
    thresholds = [32,64,128]
    images = [img3]
    for t in thresholds:
        _, img = cv2.threshold(img3, thresh=t, maxval=np.max(img3), type=cv2.THRESH_BINARY)
        images.append(img)
    titles = [f"Binary Image T={t}" for t in thresholds]
    titles = ["Original Image"] + titles
    title = "Binary Thresholding at Various Threshold Values"
    return plot_images(images=images, titles=titles, title=title)

thresholds = [32,64,128]
fig = plot_binary_images(image=img3, thresholds=thresholds)
glue("various_thresholds", fig)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 13[0m
[1;32m     10[0m     [38;5;28;01mreturn[39;00m plot_images(images[38;5;241m=[39mimages, titles[38;5;241m=[39mtitles, title[38;5;241m=[39mtitle)
[1;32m     12[0m thresholds [38;5;241m=[39m [[38;5;241m32[39m,[38;5;241m64[39m,[38;5;241m128[39m]
[0;32m---> 13[0m fig [38;5;241m=[39m [43mplot_binary_images[49m[43m([49m[43mimage[49m[38;5;241;43m=[39;49m[43mimg3[49m[43m,[49m[43m [49m[43mthresholds[49m[38;5;241;43m=[39;49m[43mthresholds[49m[43m)[49m
[1;32m     14[0m glue([38;5;124m"[39m[38;5;124mvarious_thresholds[39m[38;5;124m"[39m, fig)

Cell [0;32mIn[2], line 10[0m, in [0;36mplot_binary_images[0;34m(image, thresholds)[0m
[1;32m      8[0m titles [38;5;241m=[39m [[38;5;124m"[39m[38;5;124mOriginal Image[39m[38;5;124m"[39m] [38;5;241m+[39m titles
[1;32m      9[0m title [38;5;241m=[39m [38;5;124m"[39m[38;5;124mBinary Thresholding at Various Threshold Values[39m[38;5;124m"[39m
[0;32m---> 10[0m [38;5;28;01mreturn[39;00m [43mplot_images[49m(images[38;5;241m=[39mimages, titles[38;5;241m=[39mtitles, title[38;5;241m=[39mtitle)

[0;31mNameError[0m: name 'plot_images' is not defined
NameError: name 'plot_images' is not defined

